config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doctors
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :doctors, through: :appointments
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointements_controller.rb
class AppointmentsController < ApplicationController
   before_action :set_appointment, except: [:index, :new, :create]
   def set_appointment
     @appointment = Appointment.find(params[:id])
   end

   def index
     @appointments = Appointment.all
   end

   def new
     @appointment = Appointment.new
   end

   def create
     Appointment.create(appointment_params)
     redirect_to appointments_path
   end

   def edit
   end

   def update
     @appointment.update(appointment_params)
     redirect_to appointments_path
   end

   def destroy
     @appointment.destroy
     redirect_to appointments_path
   end

   private
   def appointment_params
     params.require(:appointment).permit(:patient_id, :doctor_id, :appointment_time)
   end
end

app/controllers/appointment_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, except: [:index, :new, :create]
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
  end

  def create
    Appointment.create(appointment_params)
    redirect_to appointments_path
  end

  def edit
  end

  def update
    @appointment.update(appointment_params)
    redirect_to appointments_path
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private
  def appointment_params
    params.require(:appointment).permit(:patient_id, :doctor_id, :appointment_time)
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :get_appointment, only: [:show, :edit, :update, :destroy]

  def get_appointment
    @appointment = Appointment.find(params[:id])
  end

  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new
    docs = Doctor.all
    pats = Patient.all
    @docarray = docs.map { |doc| [doc.name, doc.id] }
    @patarray = pats.map { |pat| [pat.name, pat.id]}
  end

  def create
    Appointment.create!(appointment_params)
    redirect_to appointments_path
  end

  def edit
  docs = Doctor.all
  pats = Patient.all
  @docarray = docs.map { |doc| [doc.name, doc.id] }
  @patarray = pats.map { |pat| [pat.name, pat.id]}
  end

  def update
  @appointment.update!(appointment_params)
  redirect_to appointments_path
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :time)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, except: [:index, :new, :create]
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def index
    @doctors = Doctor.all
  end

  def show
    @appointments = Appointment.where(doctor_id: params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    Doctor.create(doctor_params)
    redirect_to doctors_path
  end

  def edit
  end

  def update
    @doctor.update(doctor_params)
    redirect_to doctor_path(@doctor)
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :specialty)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, except: [:index, :new, :create]
  def index
    @patients = Patient.all
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def show
    @appointments = Appointment.where(patient_id: params[:id])

  end

  def new
    @patient = Patient.new
  end

  def create
    Patient.create(patient_params)
    redirect_to patients_path
  end

  def edit
  end

  def update
    @patient.update(patient_params)
    redirect_to patient_path(@patient)
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :age, :gender)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :get_visit, only: [:show, :edit, :update, :destroy]

  def get_visit
    @visit = Visit.find(params[:id])
  end

  def index
    @visits = Visit.all
  end

  def show
  end

  def new
    @visit = Visit.new
    @docs = Doctor.all.map{|d| [d.name, d.id]}
    @pats = Patient.all.map{|p| [p.name, p.id]}
  end

  def create
    Visit.create!(visit_params)
    # render plain: params.inspect
    redirect_to visits_path
  end

  def edit
    @docs = Doctor.all.map{|d| [d.name, d.id]}
    @pats = Patient.all.map{|p| [p.name, p.id]}
  end

  def update
    @visit.update(visit_params)
    redirect_to visit_path
  end

  def destroy
    @visit.destroy

    redirect_to visits_path
  end

private
  def visit_params
    params.require(:visit).permit(:doctor_id, :patient_id, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
  <%= f.label :doctor %>
  <%= f.select :doctor_id, @docarray%><br/><br/>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patarray %><br/><br/>
  <%= f.label :time %>
  <%= f.datetime_select :time %><br/><br/>
  <%= f.submit %>
<% end %>

app/views/appointments/_form.index.erb
<%= form_for @appointment do |f| %>

<%= f.select :patient_id, Patient.all.collect { |patient| [patient.name, patient.id] }  %>
<%= f.select :doctor_id, Doctor.all.collect { |doctor| [doctor.name, doctor.id] }  %>

<%= f.time_select :appointment_time %>

<%= f.submit %>
<% end %>

app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<%= render 'form' %>

app/views/appointments/index.html.erb
<h1>All Appointments<%= link_to '(+)', new_appointment_path %></h1>

<ul>
  <% @appointments.order(:time).reverse_order.each do |appointment| %>
    <li>
      <%= appointment.doctor.name %> <%= appointment.time %> <%= link_to "Delete", appointment, method: :delete %>
      <%= link_to "Edit", edit_appointment_path(appointment) %>
      <%= link_to "Show", appointment %>
    </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>New Appointments</h1>
<%= render 'form' %>

app/views/appointments/show.html.erb
<h1>Show Appointment</h1>
<p>Doctor:      <%= @appointment.doctor.name %></p>
<p>Patient:      <%= @appointment.patient.name %></p>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>

  <p><%= f.label :specialty %>
  <%= f.text_field :specialty %></p>

  <p><%= f.submit %></p>
<% end %>

app/views/doctors/edit.html.erb
<h2> Editing Info for Dr. <%= @doctor.name %> </h2>
<%= render "form" %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<h2> <%= link_to "All Patients", patients_path %> </h2>
<h3> <%= link_to "Hire New Doctor", new_doctor_path %> </h3>
<h3> <%= link_to "All Appointments", appointments_path %></h3>

<%@doctors.each do |doctor| %>
<div>
  <%=link_to "Dr. #{doctor.name}", doctor_path(doctor) %> | <%= link_to "Make an Appointment", new_appointment_path %>
</div>
<%end %>

app/views/doctors/new.html.erb
<h2>Hire new doctor</h2>
<%= render "form" %>

app/views/doctors/show.html.erb
<h1>Appointments for Dr. <%= @doctor.name %></h1>
<h2> <%= link_to "All Doctors", doctors_path %> </h2>


<h2> Specialty: <%= @doctor.specialty %> </h2>
<%= link_to "Edit #{@doctor.name}", edit_doctor_path(@doctor)  %>
<%= link_to "Fire #{@doctor.name}", doctor_path(@doctor),
  method: :delete, data: {confirm: "Give unemployment?"}  %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedoc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1 class="redcross"> + </h1>
  <h1 class="header">Dr. Manny's Group Practice</h1>
  <h2 class="header slogan"> Many Doctors, Many Patients, Many Treatments </h2>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>

  <p><%= f.label :age %>
  <%= f.text_field :age %></p>

  <p><%= f.label :gender %>
  <%= f.text_field :gender %></p>

  <p><%= f.submit %></p>
<% end %>

app/views/patients/edit.html.erb
<h2>Editing Info for <%= @patient.name %> </h2>
<%= render 'form' %>

app/views/patients/index.html.erb
<h2> Showing Patients </h2>
<h3> <%= link_to "All Doctors", doctors_path %> | <%= link_to "All Appointments", appointments_path %> </h3>


<% @patients.each do |patient| %>

<div class="patient">
  <%= link_to patient.name, patient_path(patient) %>
</div>
<% end  %>

<h3> <%= link_to "Admit New Patient", new_patient_path %> </h3>

app/views/patients/new.html.erb
<h2>Enroll New Patient</h2>
<%= render 'form' %>

app/views/patients/show.html.erb
<h1>Information for <%= @patient.name %></h1>
<h2> <%= link_to "All Patients", patients_path %> </h2>

<div class="">
  Age: <%= @patient.age %>,&nbsp;&nbsp;
  Gender: <%= @patient.gender  %>,&nbsp;&nbsp;
  <%= link_to "View Upcoming Appointments: ", '/patients/appointments/'%>

</div>

<h2>Appointments:</h2>
<% @patient.appointments.each do |appointment| %>
  <p> <%= link_to appointment.appt_time, appointment_path(appointment) %></p>
  <p> Dr. <%= appointment.doctor.name  %></p>
  <p>At: <%= appointment.appt_time %></p>

  <% end %>

<%= link_to "Edit #{@patient.name}", edit_patient_path(@patient) %>
<%= link_to "Remove #{@patient.name}", patient_path(@patient),
  method: :delete, data: {confirm: "Remove from practice?"}  %>

app/views/visits/_form.html.erb
<%= form_for @visit do |f| %>
<%= f.label :doctor %>
<%= f.select :doctor_id, @docs %><br/><br/>
<%= f.label :patient %>
<%= f.select :patient_id, @pats %><br/><br/>
<%= f.label :date %>
<%= f.datetime_select :time %><br/><br/>

<%= f.submit %>
<% end %>

app/views/visits/destroy.html.erb
<h1>Visits#destroy</h1>
<p>Find me in app/views/visits/destroy.html.erb</p>

app/views/visits/edit.html.erb
<h1>Edit Visit</h1>
<%= render 'form' %>

app/views/visits/index.html.erb
<h1>All Visits <%= link_to "(+)", new_visit_path %></h1>
<ul>
<% @visits.order(:time).reverse_order.each do |visit| %>
  <li><%= visit.patient.name %> - <%= visit.doctor.name %> - <%= visit.time %><%= link_to "Details", visit %>  <%= link_to "Delete", visit, method: :delete %>   <%= link_to "Edit", edit_visit_path(visit) %></li>
<% end %>
</ul>

app/views/visits/new.html.erb
<h1>New Visit</h1>
<%= render 'form' %>

app/views/visits/show.html.erb
<h1>Visit Details</h1>
<p>Doctor: <%= @visit.doctor.name %></p>
<p>Patient: <%= @visit.patient.name %></p>
<p>Time: <%= @visit.time %></p>
<%= link_to "All Visits", visits_path %>

app/views/visits/update.html.erb
<h1>Visits#update</h1>
<p>Find me in app/views/visits/update.html.erb</p>